apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
type: Opaque
data:
  #api-key: 49436ecad34d7cf4274a336bb4a54b6e78fc3
  #api-token: "4p2W-aIqDTMkUHEdX6ZoPlR6SZ9pF0ANEVsM2qLu" # base64 encoded api-key
  api-token: "NHAyVy1hSXFEVE1rVUhFZFg2Wm9QbFI2U1o5cEYwQU5FVnNNMnFMdQ=="