apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: nginx2  # Your namespace
spec:
  selector:
    app: nginx  # Label your deployment with this
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
