apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
          - containerPort: 80
          - containerPort: 443  # Expose HTTPS port
        volumeMounts:
          - name: nginx-certificate
            mountPath: /etc/nginx/certs
            readOnly: true
        env:
          - name: CERT_NAME
            value: "nginx2"  # Name of the certificate
          - name: CERT_NAMESPACE
            value: "nginx2"  # Namespace of the certificate
      volumes:
        - name: nginx-certificate
          secret:
            secretName: nginx2  # Secret where the TLS cert is stored
